djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from demosite import views
from demosite.views import demo_page
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from demosite.views import login_view
from django.urls import reverse_lazy



urlpatterns = [
    path('', views.demo_page, name='demo'),
    path('admin/', admin.site.urls),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    #loginForm
    path('form_submit/', views.form_submit, name='form_submit'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reg_submit/',views.reg_submit, name='reg_submit'),
    path('user/', views.dashboard, name='user'),
    #корзина
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('save_cart/', views.save_cart, name='save_cart'),
    path('delete_cart/', views.delete_cart, name='delete_cart'),
    #восстановление пароля
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    #перенос склад-прод
    path('manage_warehouse/', views.manage_warehouse, name='manage_warehouse'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# from demosite.apps import DemositeConfig
# DemositeConfig.ready()

djangoProject/demosite/models.py
from django.db import models
from django.contrib.auth.models import User


#когда купил
class Buyer(models.Model):
    name = models.CharField(max_length=25, blank=False)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=25, blank=False)
    buyer_message = models.TextField(blank=True, max_length=255)
    selected_product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0)
    def __str__(self):
        return f"{self.name} - {self.selected_product.name} ({self.quantity})"


#кнопка купить
class RegistrationForm(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        unique_together = ('email',)
    
#Регистрация 
class RegisterForm(models.Model):
    login = models.CharField(max_length=25)
    email = models.EmailField(max_length=25)
    password = models.CharField(max_length=25)
    confirmPassword = models.CharField(max_length=25)
    
# product
class Product(models.Model):
    MATERIAL_CHOICES = [
        ("1", "золотой"),
        ("2", "Серебряный"),
        ("3", "Жемчуг"),
        ("4", "Платина"),
        ("5", "Алмаз"),
        ("6", "Медь")
    ]
    name = models.CharField(max_length=255, blank=True)
    id = models.IntegerField(primary_key=True)
    price = models.IntegerField()
    description = models.TextField(max_length=700)
    material = models.CharField(max_length=1, choices=MATERIAL_CHOICES, blank=True)
    image = models.ImageField(upload_to='media/products/')
    
    def __str__(self):
        return f"Продукт {self.name}, ID {self.id}"

#корзина
class UserCart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='SelectedProduct')
    name = models.CharField(max_length=100, default='Корзина')
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    def __str__(self):
        return f"Карточка пользователя {self.user}"
#остаток товара
class Stock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.product.name} - {self.quantity} в остатке"


#соранение корзины
class SelectedProduct(models.Model):
    user_cart = models.ForeignKey(UserCart, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user_cart', 'product',)
        
    def __str__(self):
        return f"Товары {self.user_cart.user}"

#Авторизация
class User(models.Model):
    username = models.TextField(max_length=25)
    password = models.CharField(max_length=25)

#Модель переноса   
class Warehouse(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.update_stock()

    def update_stock(self):
        stock, _ = Stock.objects.get_or_create(product=self.product)
        print('self.quantity ', self.quantity)
        print('stock.quantity ', stock.quantity)
        stock.quantity = stock.quantity - self.quantity
        stock.save()
    def __str__(self):
        return f"{self.product.name} на складе {self.quantity} шт"

templates/demo.html
<!DOCTYPE html>
<html>
<head>
    <title>Ювелирный магазин</title>
    {% load static %}
    {% block css_additional%}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% endblock %}
</head>

<button id="open-registration-button" onclick="toggleRegForm()" class="buttons-text registration-button">Регистрация</button>
<button id="open-form-button" onclick="window.location.href='{% url 'login' %}'" class="buttons-text authorization-button">Авторизация</button>

<div id="reg-container" class='show' style="display: none;">
    <form method="post" action="{% url 'reg_submit' %}">
        {% csrf_token %}
        
        <div class="form-field">
            <label for="login">Логин:</label>
            <input type="text" id="login" name="login">
        </div>
        
        <div class="form-field">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email">
        </div>
        
        <div class="form-field">
            <label for="password">Пароль:</label>
            <input type="password" id="password" name="password">
        </div>
        
        <div class="form-field">
            <label for="confirmPassword">Подтверждение пароля:</label>
            <input type="password" id="confirmPassword" name="confirmPassword">
        </div>
        
        <button type="submit">Зарегистрироваться</button>
    </form>
</div>
   


        
    <div class="header">
        <h1>Jevelry World</h1>
        <!-- djangoForm -->
        
            <div id="form-container" class='show' style="display: none;" >
                <form method="post" action="{% url 'form_submit' %}">
                {% csrf_token %}
                <!-- поля фомры -->

                <div class = "form-field">
                    <label for="username">Имя пользователя:</label>
                    <input type="text" id="username" name="username">
                </div>
                
                <div class = "form-field">
                    <label for="password">Пароль:</label>
                    <input type="password" id="password" name="password">
                </div>  
                              
                <button type="submit" onclick="registrationAccepted()">Авторизация</button>
        
                </form>
            </div>
            <div class="overlay" id="overlay"></div>
    </div>

    <div class="background-image"></div>

    <!--отображение продуктов -->
    <div class="product-list">
        {% for product in products %}
        <div class="product">
            <h3>{{ product.name }}</h3>
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image">
            <div class="product-content">    
                <p>{{ product.description }}</p>
                <p>Цена: {{ product.price }} руб</p>
<<<<<<< HEAD
=======
                <p>Остаток: {{ product.remaining_quantity }}</p>
>>>>>>> b5b69d5ebaa383dfce01b65de7d0cb7f0b09e35e
                <button class="buy-button" onclick="toggleRegForm('{{ product.id }}')">Купить</button>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="about-us">
        <h2>О нас</h2>
        <p>Мы - самый лучший ювелирный магазин!</p>
        <p>Покупайте наши украшения. После оформления покупки с Вами свяжется специалист.</p>
    </div>

    
    <div id="successMessage" style="display: none; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); font-size:60px; background-color: green">
        Ваша заявка принята
    </div>
<script src="{% static 'script.js' %}"></script>

</body>
</html>

templates/login.html
<!-- user.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
    {% load static %}
    {% block css_additional %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% endblock %}
</head>
<body>
    <div class="header">
        <h1>Добро пожаловать, {{ user.username }} !</h1>
        <a href="{% url 'logout' %}">Выйти</a>
    </div>
    <div class="product-list">
        {% for product in products %}
        <div class="product">
            <h3>{{ product.name }}</h3>
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image">
            <div class="product-content">    
                <p>{{ product.description }}</p>
                <p>Цена: {{ product.price }} руб</p>
                <!-- Pass the product ID and name as data attributes -->
                <button class="buy-button" data-product-id="{{ product.id }}" data-product-name="{{ product.name }}">Купить</button>
            </div>
        </div>
        {% endfor %}
    </div>

<<<<<<< HEAD
    <div class="user-cart">
        <h3>Корзина</h3>
        {% for item in request.user.selectedproduct_set.all %}
        <div data-product-id="{{ item.product.id }}" class="cart-item">
            <p>{{ item.product.name }} - <span class="product-quantity">{{ item.quantity }}</span></p>
            <!-- Add a delete button for each cart item -->
            <button class="delete-button" data-product-id="{{ item.product.id }}">Удалить</button>
        </div>
        {% endfor %}
    </div>   
=======
    <div class="login-form">
        <h2>Авторизация</h2>
        <form method="post" action="{% url 'form_submit' %}">
            {% csrf_token %}
            <div class="form-field">
                <label for="username">Имя пользователя:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-field">
                <label for="password">Пароль:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Войти</button>
            <p><a href="{% url 'password_reset' %}">Забыли пароль?</a></p>
        </form>
    </div>
>>>>>>> b5b69d5ebaa383dfce01b65de7d0cb7f0b09e35e

    <div class="about-us">
        <h2>О нас</h2>
        <p>Мы - самый лучший ювелирный магазин!</p>
        <p>Покупайте наши украшения. После оформления покупки с Вами свяжется специалист.</p>
    </div>
    <!-- Your dashboard content goes here -->

    <script src="{% static 'buy_product.js' %}"></script>
</body>
</html>

templates/password_reset_confirm.html
<!DOCTYPE html>
<html>
<head>
    <title>Сброс пароля</title>
    {% load static %}
    {% block css_additional %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% endblock %}
</head>
<body>
    <div class="header">
        <h1>Jevelry World</h1>
    </div>

    <div class="login-form">
        <h2>Сброс пароля</h2>
        <form id="reset-form" method="post" action="{% url 'form_submit' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-field">
                <label for="email">Введите email:</label>
                <input type="text" id="email" name="email" required>
            </div>
            <button type="submit">Сбросить пароль</button>
        </form>
    </div>

    <script src="{% static 'script.js' %}"></script>
    <script>
        document.getElementById('reset-form').addEventListener('submit', function(event) {
            if (!validateEmail(document.getElementById('email').value)) {
                event.preventDefault();
                alert('Пожалуйста, введите корректный email.');
            }
        });

        function validateEmail(email) {
            const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            return regex.test(email);
        }
    </script>
</body>
</html>

templates/user.html
<<<<<<< HEAD
=======

>>>>>>> b5b69d5ebaa383dfce01b65de7d0cb7f0b09e35e
<!-- user.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
    {% load static %}
    {% block css_additional %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% endblock %}

</head>
<body>
    <div class="header">
        <h1>Добро пожаловать, {{ user.username }} !</h1>
        <a href="{% url 'logout' %}">Выйти</a>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="product-list">
            {% for product in products %}
            <div class="product">
                <h3>{{ product.name }}</h3>
                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image">
                <div class="product-content">    
                    <p>{{ product.description }}</p>
                    <p>Цена: {{ product.price }} руб</p>
<<<<<<< HEAD
                    <!-- Pass the product name to the buyProduct function -->
                    <button class="buy-button" onclick="buyProduct('{{ product.id }}', '{{ product.name }}', event)">Купить</button>
                </div>
=======
                    <p>Остаток: {{ product.remaining_quantity }}</p>
                    <button class="buy-button" onclick="buyProduct('{{ product.id }}', '{{ product.name }}', event)">Купить</button>
                </div>
            </div>
            {% endfor %}
        <p>Остаток: {{ product.remaining_quantity }}</p>
        </div>
    </form>

    <div class="user-cart">
        <h3>Корзина пользователя</h3>
        {% for item in request.user.selectedproduct_set.all %}
        <div data-product-id="{{ item.product.id }}" class="cart-item">
            <p>{{ item.product.name }} - <span class="product-quantity">{{ item.quantity }} шт</span></p>
            
            <button class="delete-button" onclick="deleteProduct('{{ item.product.name }}', event)">Удалить</button>
            
            <input type="number" min="1" value="{{ item.quantity }}" class="product-quantity-input" data-product-id="{{ item.product.id }}">
        </div>
        {% endfor %}
        <button class="buy-in-cart-button" onclick="saveCart()">Сохранить корзину</button>
    </div> 




    <div class="saved-cart-items">
        {% for user_cart in saved_carts %}
        <div class="saved-cart-item">
            <h4>Корзина {{user.username}}</h4>
            <button class="show-cart-button" onclick="showCart('{{ user_cart.id }}')">Показать</button>
            <div class="cart-products" id="cart-products-{{ user_cart.id }}" style="display: none;">
                <ul>
                    <button class="delete-cart-button" onclick="deleteCart('{{ user_cart.id }}')">Удалить корзину</button>
                    {% for selected_product in user_cart.selectedproduct_set.all %}
                    <li>{{ selected_product.product.name }} - {{ selected_product.quantity }} шт</li>
            
                    {% endfor %}
                
                </ul>
                <p>Итоговая стоимость: {{ user_cart.total_amount }} руб<p>
>>>>>>> b5b69d5ebaa383dfce01b65de7d0cb7f0b09e35e
            </div>
            {% endfor %}
        </div>
    </form>

    <div class="user-cart">
        <h3>Корзина пользователя</h3>
        {% for item in request.user.selectedproduct_set.all %}
        <div data-product-id="{{ item.product.id }}" class="cart-item">
            <p>{{ item.product.name }} - <span class="product-quantity">{{ item.quantity }}</span></p>
            <!-- Add a delete button for each product -->
            <button class="delete-button" onclick="deleteProduct('{{ item.product.name }}', event)">Удалить</button>
        </div>
        {% endfor %}
<<<<<<< HEAD
    </div> 
=======
    </div>




>>>>>>> b5b69d5ebaa383dfce01b65de7d0cb7f0b09e35e

    <div class="about-us">
        <h2>О нас</h2>
        <p>Мы - самый лучший ювелирный магазин!</p>
        <p>Покупайте наши украшения. После оформления покупки с Вами свяжется специалист.</p>
    </div>
<<<<<<< HEAD
    <!-- Your dashboard content goes here -->

    <script src="{% static 'buy_product.js' %}"></script>
=======
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="{% static 'delete_cart.js' %}"></script>
    <script src="{% static 'buy_product.js' %}"></script>
    <script src="{% static 'save_cart.js' %}"></script>
>>>>>>> b5b69d5ebaa383dfce01b65de7d0cb7f0b09e35e
    <script src="{% static 'script.js' %}"></script>
</body>
</html>

templates/warehouse_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Manage Warehouse</title>
</head>
<body>
    <h1>Manage Warehouse</h1>
    
    <form method="post">
        {% csrf_token %}
        
        <label for="product">Product:</label>
        <select name="product" required>
            <option value="">Select a product</option>
            {% for product in products %}
                <option value="{{ product.id }}">{{ product.name }}</option>
            {% endfor %}
        </select>
        
        <label for="quantity">Quantity:</label>
        <input type="number" name="quantity" required>
        
        <button type="submit">Submit</button>
    </form>
    
    <h2>Warehouse Entries:</h2>
    <ul>
        {% for warehouse in warehouses %}
            <li>{{ warehouse.product.name }} - {{ warehouse.quantity }}</li>
        {% endfor %}
    </ul>
</body>
</html>